name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: MinSizeRel

jobs:
  # === Windows PRO ===
  windows-pro:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Build
        shell: cmd
        run: |
          git clone --recursive https://github.com/nesbox/TIC-80 && cd TIC-80/build
          cmake -G "Visual Studio 16 2019" -DBUILD_SDLGPU=On -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DBUILD_PRO=On ..
          cmake --build . --config %BUILD_TYPE% --parallel

      - name: Create hash
        run: git rev-parse HEAD > rev-hash.txt

      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        name: Delete latest alpha tag and release
        with:
          tag_name: alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Sleep for 5 seconds, to allow the tag to be deleted (why?)
        run: sleep 5s    
        shell: bash
  
      - uses: ncipollo/release-action@v1.12.0
        name: Create new tag and release and upload artifacts
        with:
          name: alpha
          commit: main
          tag: alpha
          prerelease: true
          artifacts: "tic-80/build/bin/tic80.exe"
          body: Latest build of some shit.
          token: ${{ secrets.GITHUB_TOKEN }}
