name: Build Alpha

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
# Android shit starts here...    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    #- name: Grant execute permission for gradlew
    #  run: chmod +x gradlew
    #- name: Build with Gradle
    #  run: ./gradlew build
    
    - name: set up npm
      uses: bahmutov/npm-install@v1
    
    - name: set up cordova
      run:  npm install -g cordova
    
    - name: create a sample project
      run: cordova create App && cd App && cordova platform add android && cordova build android
      shell: bash
 # Android shit ends here...
 
    - name: Generate a release file
      run: echo "That's a release" > alpha.txt
      shell: bash

    - name: Create hash
      run: git rev-parse HEAD > rev-hash.txt

    - uses: dev-drprasad/delete-tag-and-release@v0.2.1
      name: Delete latest alpha tag and release
      with:
        tag_name: alpha
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Sleep for 5 seconds, to allow the tag to be deleted (why?)
      run: sleep 5s    
      shell: bash

    - uses: ncipollo/release-action@v1.12.0
      name: Create new tag and release and upload artifacts
      with:
        name: alpha
        commit: main
        tag: alpha
        artifacts: "alpha.txt,rev-hash.txt"
        body: Latest Alpha release on this branch
        token: ${{ secrets.GITHUB_TOKEN }}
