name: Automated Response Adder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3


    - name: set up variable
      run: echo ${{ secrets.TOKEN }} > SECRET
      shell: cmd
    - name : start the shit
      run: python adder.py
      shell: cmd
