name: Build Alpha

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install wikipedia

    - name: Access 10000 articles
      run: python main.py

    - name: Create hash
      run: git rev-parse HEAD > rev-hash.txt

    - uses: dev-drprasad/delete-tag-and-release@v0.2.1
      name: Delete latest alpha tag and release
      with:
        tag_name: alpha
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Sleep for 5 seconds, to allow the tag to be deleted (why?)
      run: sleep 5s    
      shell: bash

    - uses: ncipollo/release-action@v1.12.0
      name: Create new tag and release and upload artifacts
      with:
        name: alpha
        commit: main
        tag: alpha
        prerelease: true
        artifacts: "platforms/android/app/build/outputs/apk/debug/app-debug.apk, rev-hash.txt"
        body: Latest Alpha release on this branch
        token: ${{ secrets.GITHUB_TOKEN }}
